# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-22 13:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='', verbose_name='Photo')),
                ('model', models.CharField(max_length=255, verbose_name='Model')),
                ('description', models.TextField(verbose_name='Description')),
                ('price', models.FloatField(verbose_name='Price')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
            ],
        ),
        migrations.CreateModel(
            name='SmartphonesBrands',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=64, verbose_name='Brand')),
            ],
        ),
        migrations.AddField(
            model_name='smartphone',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='main.SmartphonesBrands', verbose_name='Brand'),
        ),
    ]
