# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 15:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Smartphone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='static/img/', verbose_name='Photo')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Text')),
                ('price', models.FloatField(verbose_name='Price')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Created date')),
            ],
        ),
    ]
