# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-25 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='smartphone',
            options={'verbose_name': 'Smartphone', 'verbose_name_plural': 'Smartphones'},
        ),
        migrations.AddField(
            model_name='smartphone',
            name='in_stock',
            field=models.BooleanField(default=True, verbose_name='In stock'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8, verbose_name='Price'),
        ),
    ]
