# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-03-11 07:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='voted_posts',
            field=models.ManyToManyField(to='products.Product', verbose_name='Liked posts'),
        ),
    ]
